import type { ParkingSubZone } from "@/types/parking";

export const mockParkingDetailsByZone: Record<string, ParkingSubZone[]> = {
  A: [
    {
      id: "A-1",
      name: "A-1",
      rowNumber: 1,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 40,
      occupied: 18,
      free: 22,
      skipped: 0,
      car: {
        occupied: 12,
        free: 10,
      },
      motorcycle: {
        occupied: 6,
        free: 12,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 18 / 40,
      status: "available",
    },
    {
      id: "A-2",
      name: "A-2",
      rowNumber: 2,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 35,
      occupied: 25,
      free: 10,
      skipped: 0,
      car: {
        occupied: 16,
        free: 5,
      },
      motorcycle: {
        occupied: 9,
        free: 5,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 25 / 35,
      status: "nearly-full",
    },
    {
      id: "A-3",
      name: "A-3",
      rowNumber: 3,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 45,
      occupied: 19,
      free: 26,
      skipped: 0,
      car: {
        occupied: 12,
        free: 20,
      },
      motorcycle: {
        occupied: 7,
        free: 6,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 19 / 45,
      status: "available",
    },
  ],
  B: [
    {
      id: "B-1",
      name: "B-1",
      rowNumber: 1,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 30,
      occupied: 22,
      free: 8,
      skipped: 0,
      car: {
        occupied: 15,
        free: 4,
      },
      motorcycle: {
        occupied: 7,
        free: 4,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 22 / 30,
      status: "nearly-full",
    },
    {
      id: "B-2",
      name: "B-2",
      rowNumber: 2,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 25,
      occupied: 18,
      free: 7,
      skipped: 0,
      car: {
        occupied: 14,
        free: 3,
      },
      motorcycle: {
        occupied: 4,
        free: 4,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 18 / 25,
      status: "nearly-full",
    },
    {
      id: "B-3",
      name: "B-3",
      rowNumber: 3,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 25,
      occupied: 21,
      free: 4,
      skipped: 0,
      car: {
        occupied: 16,
        free: 3,
      },
      motorcycle: {
        occupied: 5,
        free: 1,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 21 / 25,
      status: "nearly-full",
    },
  ],
  C1: [
    {
      id: "C1-1",
      name: "C1-1",
      rowNumber: 1,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 20,
      occupied: 19,
      free: 1,
      skipped: 0,
      car: {
        occupied: 12,
        free: 1,
      },
      motorcycle: {
        occupied: 7,
        free: 0,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 19 / 20,
      status: "full",
    },
    {
      id: "C1-2",
      name: "C1-2",
      rowNumber: 2,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 20,
      occupied: 18,
      free: 2,
      skipped: 0,
      car: {
        occupied: 12,
        free: 1,
      },
      motorcycle: {
        occupied: 6,
        free: 1,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 18 / 20,
      status: "full",
    },
    {
      id: "C1-3",
      name: "C1-3",
      rowNumber: 3,
      timestamp: "2026-03-20T10:15:00+07:00",
      total: 20,
      occupied: 19,
      free: 1,
      skipped: 0,
      car: {
        occupied: 12,
        free: 0,
      },
      motorcycle: {
        occupied: 7,
        free: 1,
      },
      snapLink: null,
      hasData: true,
      occupancyRate: 19 / 20,
      status: "full",
    },
  ],
  D: [],
};
