import type { ParkingZone } from "@/types/parking";

export const mockParkingZones: ParkingZone[] = [
  {
    id: "A",
    name: "โซน A",
    rowNumber: 1,
    timestamp: "2026-03-20T10:15:00+07:00",
    total: 120,
    occupied: 62,
    free: 58,
    skipped: 0,
    car: {
      occupied: 40,
      free: 35,
    },
    motorcycle: {
      occupied: 22,
      free: 23,
    },
    snapLink: null,
    hasData: true,
    occupancyRate: 62 / 120,
    status: "available",
  },
  {
    id: "B",
    name: "โซน B",
    rowNumber: 2,
    timestamp: "2026-03-20T10:15:00+07:00",
    total: 80,
    occupied: 61,
    free: 19,
    skipped: 0,
    car: {
      occupied: 45,
      free: 10,
    },
    motorcycle: {
      occupied: 16,
      free: 9,
    },
    snapLink: null,
    hasData: true,
    occupancyRate: 61 / 80,
    status: "nearly-full",
  },
  {
    id: "C1",
    name: "โซน C1",
    rowNumber: 3,
    timestamp: "2026-03-20T10:15:00+07:00",
    total: 60,
    occupied: 56,
    free: 4,
    skipped: 0,
    car: {
      occupied: 36,
      free: 2,
    },
    motorcycle: {
      occupied: 20,
      free: 2,
    },
    snapLink: null,
    hasData: true,
    occupancyRate: 56 / 60,
    status: "full",
  },
  {
    id: "D",
    name: "โซน D",
    rowNumber: 4,
    timestamp: null,
    total: 0,
    occupied: 0,
    free: 0,
    skipped: 0,
    car: {
      occupied: 0,
      free: 0,
    },
    motorcycle: {
      occupied: 0,
      free: 0,
    },
    snapLink: null,
    hasData: false,
    occupancyRate: 0,
    status: "no-data",
  },
];
